#
# vars for group [windows_local]
#

# on 5985 port

ansible_user: vagrant
ansible_password: vagrant

ansible_port: 5985
ansible_connection: winrm
ansible_winrm_scheme: http
ansible_winrm_server_cert_validation: ignore

#ansible_winrm_transport: basic

# on 5986 port


